version: "3.8"

services:
  backend:
    build:
      context: ./BilinearModel_backend
    ports:
      - "8000:8000"
    networks:
      - bilinear-connection

  frontend:
    build:
      context: ./BilinearModel_frontend
    ports:
      - "5173:5173"
    networks:
      - bilinear-connection
    stdin_open: true
    tty: true

networks:
  bilinear-connection:
    driver: bridge
